# Configuration file for Core Lab Microbiome Analysis Pipeline


# On MacOS this currently doesn't support docker, as docker requires 

# Please modify the parameters below to suit your project needs

# The first run will generate a manifest files
# Please use a simple spreadsheet software to create metadata.tsv 
# and save it as a tab-delimited text file
# After the first run, you can modify other parameters as needed

# Set to conda if you 
ENVIRONMENT_TYPE: "conda"  # or "docker"

# Pick from 'NGS' or 'TGS'
SEQUENCE_TYPE: 'TGS'
# Pick from 'region_V3V4' or 'full_length' of the 16S rRNA gene region
REGION: 'full_length'

# Maximum cores used
N_THREADS: 12

# Study name, enter a unique name for your project
# !!!!!!!!!!!!!!!!!!!!!!!!!!
# DO NOT NAME DIFFERENT PROJECTS THE SAME NAME
# SNAKEMAKE WILL OVERWRITE IT
# !!!!!!!!!!!!!!!!!!!!!!!!!!

STUDY_NAME: 'Reza'

# Specify reference genome database
# Commented out databases are not supported yet
REFERENCE_DB: 
 - 'Greengenes2'
#  - 'SILVA138'
#  - 'NCBI'

# Specify grouping column name in metadata for diversity analysis
# This assumes all subsets across all levels are included in comparison
# At least one grouping column is needed, leave other empty if not needed
# If any level is crossed, all previous levels cannot be independent
FIRST_GROUPING_COLUMN: "Group"
SECOND_GROUPING_COLUMN: ""
SECOND_GROUPING_INTERACTION: "crossed"   # "crossed" or "independent"
THIRD_GROUPING_COLUMN: ""
THIRD_GROUPING_INTERACTION: "independent"    # "crossed" or "independent"


# Specify samples to not include in analysis and visualisation
# Ignored samples will still be imported, trimmed, and denoised
# But will be filtered right before taxonomy assignment
# This is done to avoid having to rerun cutadapt and dada2 steps
# A filtered_metadata.tsv file will be generated for reference
IGNORE_SAMPLES: ['C1','C2','C3','C4']

# Choose differential abundance methods to perform
# Commented out methods are not supported yet
DIFFERENTIAL_ABUNDANCE_METHOD: 
 - 'LEfSe'
  # - 'ALDEx2'
  # - 'ANCOMBC2'

# Choose whether to run PICRUSt2 for functional prediction
RUN_PICRUST2: "true" # "true" or "false"

