QT.network_private.VERSION = 5.15.8
QT.network_private.name = QtNetwork
QT.network_private.module =
QT.network_private.libs = $$QT_MODULE_LIB_BASE
QT.network_private.includes = $$QT_MODULE_INCLUDE_BASE/QtNetwork/5.15.8 $$QT_MODULE_INCLUDE_BASE/QtNetwork/5.15.8/QtNetwork
QT.network_private.frameworks =
QT.network_private.depends = core_private network
QT.network_private.uses = openssl
QT.network_private.module_config = v2 internal_module
QT.network_private.enabled_features = openssl-linked openssl linux-netlink system-proxies
QT.network_private.disabled_features = libproxy netlistmgr
QMAKE_INCDIR_GSSAPI = /home/patwuch/Documents/projects/Core-Lab-of-Human-Microbiome-TMU/main/.snakemake/conda/d22e8a215351360d6473765ea86f8ed9_/include
QMAKE_LIBS_OPENSSL = -lssl -lcrypto
QMAKE_LIBS_NETWORK = 
QMAKE_LIBS_GSSAPI = -L/home/patwuch/Documents/projects/Core-Lab-of-Human-Microbiome-TMU/main/.snakemake/conda/d22e8a215351360d6473765ea86f8ed9_/lib -lgssapi_krb5
