QT.core_private.VERSION = 5.15.8
QT.core_private.name = QtCore
QT.core_private.module =
QT.core_private.libs = $$QT_MODULE_LIB_BASE
QT.core_private.includes = $$QT_MODULE_INCLUDE_BASE/QtCore/5.15.8 $$QT_MODULE_INCLUDE_BASE/QtCore/5.15.8/QtCore
QT.core_private.frameworks =
QT.core_private.depends = core
QT.core_private.uses =
QT.core_private.module_config = v2 internal_module
QT.core_private.enabled_features = clock-gettime datetimeparser doubleconversion futimens getauxval glib glibc hijricalendar icu inotify linkat mimetype-database poll_ppoll sha3-fast
QT.core_private.disabled_features = etw futimes getentropy posix-libiconv gnu-libiconv iconv journald lttng poll_poll poll_pollts poll_select system-pcre2 renameat2 slog2 statx syslog system-doubleconversion
QMAKE_INCDIR_GLIB = /home/patwuch/Documents/projects/Core-Lab-of-Human-Microbiome-TMU/main/.snakemake/conda/d22e8a215351360d6473765ea86f8ed9_/include /home/patwuch/Documents/projects/Core-Lab-of-Human-Microbiome-TMU/main/.snakemake/conda/d22e8a215351360d6473765ea86f8ed9_/include/glib-2.0 /home/patwuch/Documents/projects/Core-Lab-of-Human-Microbiome-TMU/main/.snakemake/conda/d22e8a215351360d6473765ea86f8ed9_/lib/glib-2.0/include /home/patwuch/Documents/projects/Core-Lab-of-Human-Microbiome-TMU/main/.snakemake/conda/d22e8a215351360d6473765ea86f8ed9_/include
QMAKE_DEPENDS_ICU_CC = LIBDL
QMAKE_DEPENDS_ICU_LD = LIBDL
QMAKE_LIBS_LIBRT = 
QMAKE_LIBS_GLIB = -L/home/patwuch/Documents/projects/Core-Lab-of-Human-Microbiome-TMU/main/.snakemake/conda/d22e8a215351360d6473765ea86f8ed9_/lib -lgthread-2.0 -lglib-2.0
QMAKE_LIBS_ICU = -licui18n -licuuc -licudata
QMAKE_LIBS_LIBATOMIC = 
